### ISSUE TITLE
There are plans to add more functions?

### ISSUE THREAD

**Issue by ellipticaldoor** [remeda/remeda#10]
Thank you very much for this library, I think is really awesome.

I'm missing some utility functions from ramda like, always, isEmpty, isNil, adjust, cond and assocPath

There is a roadmap for the project?

**Comment by BetterCallSky** [comment]
Hi,

Not sure if we should add methods like `always` or `isNill`, because they can be replaced by 1-liner lamdba.
```ts
// always
x => x
```

```ts
// isNill
x => x == null
```

Methods that accept many types (string, array, object) sometimes doesn't work well with typescript, and types are not inferred correctly.

I am also not a big fan of functions like `cond` because it's better to write a standard `if` or `? :` operator.

For example:
```js
const fn = R.cond([
  [R.equals(0),   R.always('water freezes at 0°C')],
  [R.equals(100), R.always('water boils at 100°C')],
  [R.T,           temp => 'nothing special happens at ' + temp + '°C']
]);
```
can be written like
```js
const fn = (temp: number) =>
  temp === 0
    ? 'water freezes at 0°C'
    : temp === 100
      ? 'water boils at 100°C'
      : 'nothing special happens at ' + temp + '°C';
```

`Remeda` should be more like `lodash`, with proper typings, lazy pipes, and lower bundle size.  

If there are missing core functions, you can create an issue, and I will implement them. Or you can create a pull request.

Thanks!

**Comment by ellipticaldoor** [comment]
Cool! I agree with that, thank you :)

Oh! One good thing about cond is that the params in the array can be composed.

Using ternaries is harder to read, Im writing a redux reducer like that and after 5 cases is very hard to understand.
