### ISSUE TITLE
Is there a babel plugin for this lib?

### ISSUE THREAD

**Issue by zhaoyao91** [remeda/remeda#104]
like https://github.com/megawac/babel-plugin-ramda
if there is a babel plugin, it would help optimize the bundle size while allow ease of use.

**Comment by TkDodo** [comment]
It’s a good idea - i think we could just use the ramda one as a baseline, right?

**Comment by lstkz** [comment]
Tree shaking is supported by default. I think we don't need any plugins.

**Comment by TkDodo** [comment]
depends on your bundler I'd say? some don't support tree-shaking (like parcel v1.0), and it would help to transform the imports there. I am currently enforcing this manually with an eslint rule :)

**Comment by lstkz** [comment]
@TkDodo https://medium.com/@devongovett/parcel-v1-9-0-tree-shaking-2x-faster-watcher-and-more-87f2e1a70f79
I did only a quick research. Based on the above article, tree shaking is supported in Parcel, and this news is almost 3 years.

**Comment by TkDodo** [comment]
@lstkz it was just an example, and `parcel` has a `--experimental-scope-hoisting` flag to enable treeshaking, so it's still "experimental". It will be on per default in v2, but there are still many issues with it, and v2 is in alpha stage.

**Comment by Bessonov** [comment]
I'm not sure that a such plugin is a win for the community. In fact, I see it as a loss, if maintained by remeda team, because:
1. It takes time and energy from the core functionalities, which are THE value of remeda.
2. It's a waste of time, if every library implements a babel plugin instead of solving it in the right place, for example bundler. If some bundlers doesn't have tree-shaking, then it's still just matter of time. I can't imagine using a bundler without tree-shaking support or some pre/post-processing step for ALL libraries, not only through plugins for some of them.
3. I didn't used babel for years, at least not directly (for example with CRA). Therefore I'm not sure, that a tool-specific solution helps the community. If snowpack resolves some problems with monorepos, then I would like to move from [webpack + ts-loader](https://github.com/Bessonov/monorepo-starter) to snowpack + tsc.

**Comment by TkDodo** [comment]
I would also see it as a non-goal for now. If someone wants to create a separate babel-plugin repo, they can do so.
