### ISSUE TITLE
better example for lazy evaluation?

### ISSUE THREAD

**Issue by evdama** [remeda/remeda#15]
I know of course what lazy evaluation is, but I'm not sure about the example on the readme?
where exactly is the lazy evaluation in this example? is it the fact that `console.log` runs four times before the entire pipe is done? can you maybe add an inline comment were/how lazy eval happens?

**Comment by BetterCallSky** [comment]
Lazy evaluation stops processing elements if the limit is reached from functions like `R.take(3)`.

Example from the readme:
An array has 8 elements`[1, 2, 2, 3, 3, 4, 5, 6]`
We want to get the first 3 unique elements.
Because of lazy evaluation only elements `[1, 2, 2, 3]` are processed instead of full array `[1, 2, 2, 3, 3, 4, 5, 6]`.

**Comment by evdama** [comment]
ah, I see, so you've put the map with the console.log in there just to show that after four elements we're done executing...

**Comment by evdama** [comment]
did a PR https://github.com/remeda/remeda/pull/17
closing
