### ISSUE TITLE
0.0.31 breaks groupBy

### ISSUE THREAD

**Issue by nghiepit** [remeda/remeda#152]
After upgrading to `0.0.31` my code broke somewhere.
As far as I know, https://github.com/remeda/remeda/pull/143 added `Partial` to return type.
For my question, What do I need to make it work?

https://codesandbox.io/s/inspiring-glade-p2tsy?file=/src/index.ts
```ts
import * as R from "remeda";

interface Item {
  name: string;
  label: string;
}

const input: Item[] = [
  {
    name: "a",
    label: "123"
  },
  {
    name: "b",
    label: "456"
  },
  {
    name: "a",
    label: "789"
  }
];

const data = R.pipe(
  input,
  R.groupBy(R.prop("name")),
  R.mapValues(R.map(R.prop("label")))
);
```

**Comment by TkDodo** [comment]
@Bessonov can you maybe help us out here? I think the `Partial` introduced this, but I'm not totally sure what to do against it, because removing `Partial` will bring back the false positives when using string literal types as keys ...

- https://github.com/remeda/remeda/pull/143#issuecomment-963637078

**Comment by Bessonov** [comment]
@nghiepit thanks for great reproduction!
It's not helpful, but from my point of view the outcome is right, because it try to map values on `undefined` and becomes `never`. I never worked with remeda's `pipe`, so it will take time to figure it out. In the core you want to achieve this one:

```typescript
const data = R.pipe(
  input,
  R.groupBy(R.prop("name")),
  R.mapValues(v => v?.map(item => item.label))
)
```
Is there any pipeable function for `(v ?? [])`?

**Comment by TkDodo** [comment]
@Bessonov yeah that works, but I still think types should flow through. The problem with adding `undefined` via `Partial` is that when you map over it, it will give you `undefined` even though it _cannot_ be undefined, because you only map over known properties.

I thought we tested this on the PR, when we did:

```
interface MyType {
	type: 'right' | 'wrong'
}

const myTypes: MyType[] = [
	{ type: 'right' }
]

const grouped = R.groupBy(myTypes, item => item.type)

Object.entries(grouped).forEach(([, value]) => {
  console.log(value[0].type) // <-- works
})
```

Here, accessing `value` works ([playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.5.2#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg7gA7GEqbZAYxLgFkBPACr8wPAN50AkDBEkAXHADkUYAHMAFjEVwAPkoDueJqsV0Avg04QmqeCCGzUCgcNEBtALpwAvHDdSxOBlRBWU1TW0LD0trWzhVPABXUQofTAA6BIhkgCF+AAp7VxJUABo4YFYCbwA+Cqr04JIASgYAeQAjACsSThh0khYVEvys5Mpm9OxoAFEudXz8t3KAN2QAG0SSD2afOok4OCsbCHWSdPWIVXy1zZI3AAYPRtldgHo3uAAeAFofuH00AA1qhzK06EA))

However, it starts to fail as soon as you move from a string literal on `type` to a normal string, which is what @nghiepit is seing ❗ 

[playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.5.2#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg7gA7GEqbZAYxLgFkBPACr8wPAN50AkDBEkAXHFQwozAOZ0Avg04QmSuCCGzUCgcNEBtALpwAvHAtSxcGaIUByFaoAWMd3C0rbV19VTwAV1EKO0wAOjCISIAhfgAKQ3MSVAAaOGBWAlsAPjyC2NcSAEoGAHkAIwArEk4YWJIWFSzUhMjKStjsaABRLm9U1ItcgDdkABtwkitKuxKJODgdPQhZkljZiFVUmfmSCwAGK3LZZYB6G7gAHgBaJ7gKCCymd3gAd2gAaxQTH4IGgJAAhODNNU6EA)

also, we only tested with `Object.entries`, but not with things like `R.mapValues`, which has different types than `Object.entries`.

**Comment by Bessonov** [comment]
@TkDodo what do you think about `NonNullable` here:
```typescript
declare function mapValues<T extends Record<PropertyKey, any>, S>(
  fn: (value: NonNullable<T[keyof T]>, key: keyof T) => S
): (object: T) => Record<keyof T, S>;
```
? I think it would fit into iteration semantic.

**Comment by Bessonov** [comment]
> However, it starts to fail as soon as you move from a string literal on `type` to a normal string, which is what @nghiepit is seing exclamation
> 
> [playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.5.2#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg7gA7GEqbZAYxLgFkBPACr8wPAN50AkDBEkAXHFQwozAOZ0Avg04QmSuCCGzUCgcNEBtALpwAvHAtSxcGaIUByFaoAWMd3C0rbV19VTwAV1EKO0wAOjCISIAhfgAKQ3MSVAAaOGBWAlsAPjyC2NcSAEoGAHkAIwArEk4YWJIWFSzUhMjKStjsaABRLm9U1ItcgDdkABtwkitKuxKJODgdPQhZkljZiFVUmfmSCwAGK3LZZYB6G7gAHgBaJ7gKCCymd3gAd2gAaxQTH4IGgJAAhODNNU6EA)

I don't know why it happens. I try to find it out and I assume that it's more related to TS...

**Comment by TkDodo** [comment]
@Bessonov I think this would just introduce different bugs. For example, if you have null as a real potential value in your Array:

```
const obj = {
  foo: 'foo',
  bar: null
} as const

mapValues(obj, x => x.toUpperCase())
```

this would work with your proposal, but it shouldn't.

---

I think what we would need to do to make this work together is to allow `null` / `undefined` as input to `map` and similar functions. This has already been requested as a feature here:

- https://github.com/remeda/remeda/issues/147

we still haven't decided if we want that, or what e.g. `map` should return if it gets `undefined` as input 🤔 . @Bessonov what do you think?

**Comment by Bessonov** [comment]
> this would work with your proposal, but it shouldn't.

Oh, yeah, multitasking is bad ) I'm still not focused :(

> we still haven't decided if we want that

Personally, I'm still on the track that it's error prone.

I think there are multiple challenges:
1. `Object.entries(grouped).forEach` and friends doesn't remove `Partial` leftovers. Unfortunately, I didn't found any related issue on ts side to understand why this is the case.
2. Valid cases like this issue and your example with `bar: null` and how to handle them in remeda.

For the second challenge I don't have any good answer too. On it's own the behavior seems to be correct. There is just some mismatch between semantic. A piece of information like "this `undefined` comes from `groupBy` and not from original type" is missing. 

What should we do? TBH IDK. I vote for leaving it as is until there is a better way to handle it. But it makes remeda inconvenient. Probably all other libraries chosen to use wrong typings because of that.

@nghiepit do you have any idea how to deal with typings in this case?

**Comment by TkDodo** [comment]
I'm starting to think that the best solution would be to revert the PR that broke it. While its neat that grouping by something that is a number would yield the type `number` for a key, I think there is also a reason why functions like `Object.keys` always return _string_ .

Grouping by a property that is of type `'a' | 'b'` does _not_ mean that your resulting object should be of type `Record<'a' | 'b', ...>` because being a Record with a union as the key implies that all properties are set on that object - which is clearly not the case for `groupBy`, hence we added `undefined` to the value, which now breaks piping.

@lstkz what do you think?

**Comment by Bessonov** [comment]
> I'm starting to think that the best solution would be to revert the PR that broke it.

Maybe. Given the circumstances I'm fine with it.

> I think there is also a reason why functions like Object.keys always return string .

Well, it's not ts fault:
```
Object.keys({1: 'a'})
['1']
```

Therefore I don't think there is a special reason for that except of language's bad roots.

**Comment by Bessonov** [comment]
> I'm starting to think that the best solution would be to revert the PR that broke it.

Maybe. Given the circumstances I'm fine with it.

> I think there is also a reason why functions like Object.keys always return string .

Well, it's not ts fault:
```
Object.keys({1: 'a'})
['1']
```

Therefore I don't think there is a special reason for that except of language's bad roots.

**Comment by TkDodo** [comment]
I've reverted this in 0.0.32.

**Comment by nghiepit** [comment]
Hey @TkDodo @Bessonov 
Sorry, I can't be of any help.
What do you think about If create a new `groupByStrict` or `export function groupBy<T, Strict extends boolean = false>()`?

**Comment by Bessonov** [comment]
@TkDodo what do you think about @nghiepit 's:

> What do you think about If create a new groupByStrict [...]?

? I'm still on 0.0.31 because of this feature.

**Comment by TkDodo** [comment]
@Bessonov okay, let's do it :) We're fully treeshakable anyways, and `groupByStrict` could still call `groupBy` under the hood - it would just be different types, right?

But we should have good documentation about the differences / tradeoffs please :) And maybe we should just _not_ make it pipeable...

**Comment by TkDodo** [comment]
@Bessonov we now have a dedicated notation for this: similar to `map` and `map.indexed`, we now have e.g. `keys` and `keys.strict`. This is also shown in the docs:

https://remedajs.com/docs#keys

if you want to add a `strict` version of `groupBy`, please do `groupBy.strict`
