### ISSUE TITLE
More narrow type inference like Rambda?

### ISSUE THREAD

**Issue by hongquan** [remeda/remeda#157]
I like Remeda's data-first, data-last idea. But something I missed from Rambda type system, like `keys` function. To give an example, I have:

```ts
import * as Re from 'remeda'
import * as Ra from 'rambda'

export const AirConditionType = {
  temperature: 1,
  humidity: 2,
} as const

export const SoilConditionType = {
  soil_temperature: 11,
  soil_electrical_conductivity: 12,
  moisture: 13,
  soil_hydrogen_power: 14,
} as const

const a = Re.keys(Re.merge(AirConditionType, SoilConditionType))
const b = Ra.keys(Ra.merge(AirConditionType, SoilConditionType))
```

Rambda will deduce type as `("temperature" | "humidity" | "soil_temperature" | "soil_electrical_conductivity" | "moisture" | "soil_hydrogen_power")[]`, whereas Remeda yields `string[]` and I prefer Rambda output. If somewhere later I want the output to be more generic, I just cast to `string[]`.

Do you agree with the change?

**Comment by TkDodo** [comment]
`Object.keys` in `TypeScript` also just returns `string[]`, and it's by design:

- https://stackoverflow.com/questions/52856496/typescript-object-keys-return-string
- https://github.com/Microsoft/TypeScript/issues/12870
- https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208

if we were to do this, it would have to be scoped to `readonly` array, because they cannot be modified. But personally, I would wait until TS figures this out with `Object.keys`
