### ISSUE TITLE
exported namespace for easy autoimport

### ISSUE THREAD

**Issue by jasonkuhrt** [remeda/remeda#161]
Thanks for building this library!

Zod for examples allows being used by typing `z` anywhere and getting the autoimport for it.

Felt like I would want the same here for `remeda`, either `r` or `R` or `Remeda` or all of them.

IIUC in theory this should not affect tree shaking even if a consumer uses this exported namespace as member access will still determine what is tree shakable or not? Not sure about that.

**Comment by TkDodo** [comment]
I don't think I understand. You can:

```
import * as R from 'remeda'
```

and then just use `R.map` or whatever it is you want to use. it's also fully treeshakeable.

**Comment by jasonkuhrt** [comment]
That doesn't work with autoimport today. There's some unstable work out there experimenting with namespaced auto-imports but its not ready for prime time.

**Comment by TkDodo** [comment]
I guess you are talking about the extra `as z` export here?

https://github.com/colinhacks/zod/blob/004eefea58827bcf122c0517268cd11a540d207b/src/index.ts#L3

would treeshaking still work with that approach?

**Comment by jasonkuhrt** [comment]
@TkDodo yep

> would treeshaking still work with that approach?

I'm actually curious about that both in terms of:

1. What does the spec make possible
2. What do tools support today
3. What are tools committed to supporting eventually

This bit requires a bit of research at least for me.

IIUC in principal the entire ESM system is static and so namespaces should not be a problem otherwise that seems like a serious flaw in the language.

That said, given the abundance of transpiling still in production today, I'm far from sure about anything.

**Comment by jaskp** [comment]
At the very least, Rollup correctly tree-shakes it. See [repl](https://rollupjs.org/repl/?version=3.22.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QlIlN0QlMjBmcm9tJTIwJy4lMkZyZW1lZGEuanMnJTVDblIubWFwKCklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwbWFwJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnbWFwJyklMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIybWFwLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZtYXAuanMnJTVDbmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZmaWx0ZXIuanMnJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZpbHRlciUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwY29uc29sZS5sb2coJ2ZpbHRlcicpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmZpbHRlci5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGbGliLmpzJyU1Q25leHBvcnQlMjAqJTIwYXMlMjBSJTIwZnJvbSUyMCcuJTJGbGliLmpzJyUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJyZW1lZGEuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE).

I agree it is unergonomic to have to manually `import * as R from 'remeda'` since typescript won't automatically guess a namespace for it itself.

@TkDodo Under what conditions could an export such as `R` be added?

**Comment by jasonkuhrt** [comment]
Personally going to close this as it's not a big deal to re-export `r` in an application context. Others though might want to open their own issues about this :)
