### ISSUE TITLE
`piped` with basic extendable input type

### ISSUE THREAD

**Issue by HardCoreQual** [remeda/remeda#212]
Now it can be done so

```typescript
const omitId = createPipe(
  <T extends { id?: any }>(e: T) => e,
  omit(['id']),
);

const result = omitId({ id: 3, name: '_' });
```

but think can see better syntax like

```typescript
const p = createPipeWithType<{ id?: any }>(omit(['id']));
p({ id: 3, name: '_' });  // -> { name: string }
// or
const p = setInitialType<{ id?: any }>(
   createPipe(omit(['id']))
);
p({ id: 3, name: '_' });  // -> { name: string }
```

but I still not sure that it is possible to implement

**Comment by cjquines** [comment]
at least, you can write `R.identity`:

```ts
const omitId = createPipe(
  identity<T extends { id?: any }>(),
  omit(['id']),
);
```

(though this would require a data-last version of `R.identity`, which doesn't exist yet)

**Comment by cjquines** [comment]
idk what the typical workarounds to microsoft/TypeScript#10571 or microsoft/TypeScript#26242 are

**Comment by eranhirsch** [comment]
The concern here mirrors the concerns raised in #864 where `piped` (originally `createPipe`) is used to create new data-last functions. The library atm doesn't encourage this coding style to keep things simple, as it has some caveats for effective typing. Because of that, we don't have immediate plans to improve the typing for piped.
