### ISSUE TITLE
I cannot understand doc for sortBy

### ISSUE THREAD

**Issue by kimwykoff** [remeda/remeda#330]
I'm trying to convert a column sorting function implemented with ramda to remeda, but I just don't understand the docs.
The original function is like this:
```
private orderEntities(
    entities: Entity[],
    sorters: ReadonlyArray<ColumnSortingOrder>
  ): Entity[] {
    const sortWith = sorters.map(sorter =>
      sorter.state === ColumnSortingState.Ascending
        ? R.ascend(R.prop(sorter.key))
        : R.descend(R.prop(sorter.key));
    return R.sortWith(sortWith)(entities);
```
But when I try to implement this like:
```
const sorts = sorters.map(sorter =>
      [(x: Entity) => {
        if (sorter.key === 'expiryDate') {
          x.expiryDate.toISOString();
        } else if (sorter.key === 'name') {
          return x.name;
        } else { // won't happen
          return '';
        }
      }, sorter.state === ColumnSortingState.Ascending ? 'asc' : 'desc']
    );

    return R.sortBy(entities, ...sorts, sorts[0]);
```
I get 2 errors on that return line:
TS2322: Type '(array: readonly unknown[]) => unknown[]' is not assignable to type 'Entity[]'.
TS2769: No overload matches this call.<br/>Overload 1 of 2, '(sort: SortRule&lt;unknown&gt;, ...sorts: SortRule&lt;unknown&gt;[]): (array: readonly unknown[]) =&gt; unknown[]', gave the following error.<br/>Argument of type 'Entity[]' is not assignable to parameter of type 'SortRule&lt;unknown&gt;'.<br/>Type 'Entity[]' is not assignable to type 'SortProjection&lt;unknown&gt;'.<br/>Type 'Entity[]' provides no match for the signature '(x: unknown): Comparable'.<br/>Overload 2 of 2, '(array: readonly Entity[], ...sorts: SortRule&lt;Entity&gt;[]): Entity[]', gave the following error.<br/>Argument of type '(string | ((x: Entity) =&gt; string))[]' is not assignable to parameter of type 'SortRule&lt;Entity&gt;'.<br/>Type '(string | ((x: Entity) =&gt; string))[]' is not assignable to type 'SortProjection&lt;Entity&gt;'.<br/>Type '(string | ((x: Entity) =&gt; string))[]' provides no match for the signature '(x: Entity): Comparable'.

If I don't return a tuple in my sorter mapping and just return the function, then there's no problem, but then it always sorts everything in ascending order. I don't know how to make the sorts array correctly and the example shows only 1 tuple in the second position.

**Comment by eranhirsch** [comment]
As far as I remember (without running the code) you probably need to 
1. use `as const` at the end of the tuple (in the initial "sorts" mapper) so that typescript treats your array as an array of tuples and not an array of arrays. If the typing of sorts isn't correct when you use it in sortBy, Remeda won't be able to infer it.
2. You don't need that last `sorts[0]`, simply spread the array.

**Comment by kimwykoff** [comment]
@eranhirsch thanks for that. I tried this:
```
const sorts = sorters.map(sorter =>
      [(x: Entity) => x[sorter.key], sorter.state === ColumnSortingState.Descending ? 'desc' : 'asc'] as const
);
return R.sortBy(entities, ...sorts);
```
So that compiles, but when I run it, I get:
```
ERROR TypeError: fn is not a function
    at sortBy.js:40:14
    at Array.sort (<anonymous>)
    at sortBy (sortBy.js:39:46)
    at Module.f2 (_curry2.js:28:14)
```
Thanks

**Comment by eranhirsch** [comment]
It looks like you have a typing issue that isn't related to Remeda directly. I can't help you without seeing how everything is typed, you might be returning `undefined` in your mapper.

Here's an example that does work: 
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJTgMyhEcBEUCmIcAmAhpgNwBQ5MAnmDnAKIB2MwNcAvHAN7lxxMi+AFxwAzjCjAmAcwr88RYABtREqbIoBfClVr0AwhGUBXEEwDK0VrIDyUAjiicefcTCIwcozAEELBphwAD5YACIMAWRuANY41GqS0nLkOpQAxhBMEnA4LGzAOGKizKw0ANoAui5VFJnZ8GLWTsVwRqbmVrDJ9o5QVTWVuvU5TbBiLggAdCBEYAAUbmNeUGIANG7z3O6eOGtwcdRwWgCUnAB8bvzlV-xw896M+TRnHOf3h5wcXJgAFjjKZQQIIAflyU0E+DgohwU0UKhOGzudwkuy+P38gTgYMwRDE6SCPkc+MwSLu1TxcBGMHIJ2GWVGzQIkymywAQtQHs9Cus4FN+csxHTyEA

**Comment by rubencallewaert** [comment]
Unfortunately the provided example doesn't work anymore on the TS playground. Do you have a suggestion on how to get this working today?

**Comment by eranhirsch** [comment]
Sorry for taking so long to reply, @rubencallewaert! The problem with spreading the sorts is that TypeScript can't rule out that the `sorts` array is **empty** because when it is empty, it will use the data-last variant and the `entities` array will be treated as sorting criteria! Providing TypeScript with the assurance that `sorts` is not empty would solve the typing issue here:


https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJTgMyhEcBEUCmIcAmAhpgNwBQ5MAnmDnAKIB2MwNcAvHAN7lxxMi+AFxwAzjCjAmAcwr88RYABtREqbIoBfClVr0AwhGUBXEEwDK0VrIDyUAjiicefcTCIwcozAEELBphwAD5YACIMAWRuANY41GqS0nLkOpQAxhBMEnA4LGzAOGKizKw0ANoAui5VFJnZ8GLWTsVwRqbmVrDJ9o5QVTWVusDIcAAUAIQIAHQAFkRivjAAMjgLMGNNsC0ANHAAjACUh678MLNoAO4CONcMUGhQY5gAchDizVBiE5iH2hlZHJbGBiFwzEBEMBjNzA3ZuMbcdyeHB7OLUOBaE4cAB8bn45Tx-HG3kY+RoWOx4zRnA4XEwsxwymUECCAH5ctNBPg4KIcNNFCpDjtCfwJMiaXT-IE4OzMAt0kEfI4xArhUS4NUFnB6hJyH8AQ0PtsCGDpsCAELUMZ5MqFMR7aaO4FifVAA
