### ISSUE TITLE
Roadmap / contribution

### ISSUE THREAD

**Issue by SirJayEarn** [remeda/remeda#37]
#10 already raises a similar question, but is closed now. So I think this question is still open for potential contributors: **what's next?**
I like this project and for it to be a true alternative to lodash or ramda I think it should focus on ease of migration (from one of the named libraries) and provide alternatives to all the main utils.
This leads to another question: _what are the main functions?_
So just to get this conversation going,  here is what I think is missing in remeda:

`isNil`, `defaultTo`, `is`, `isEmpty`, `uniqBy`, `path`, `prop`, `propOr`, `propEq`, `nth`, `length`, `includes`, `has`, `assoc`, `assocPath`, `tail`, `init`, `debounce`, `throttle`

If this lists seems reasonable I would pick one of these from time to time and mark them as in progress (by creating an issue or something) and then create a pull request when done.

What I therefore also would find helpful, would be a short introduction about how to implement lazyness, as this is not yet completely clear to me.

**Comment by BetterCallSky** [comment]
If you think there are core functions are missing, then I will be happy to accept PRs, but some functions from lodash/ramda are 1-liners.

- `isNil`, I think it's not needed because it can be replaced with `x => x == null`
-  `defaultTo` we can add it
- `is`, not sure how to implement it, and I don't like ramda implementation https://ramdajs.com/docs/#is. Currently, I always use `typeof` or `Array.isArray`. We can discuss it in a separate issue.
- `uniqBy` we can add it
- `path`, I think it's not needed because in the new typescript version we can use `a?.b?.c` syntax
- `prop`, not sure because can be replaced with `x => x.foo`
- `propOr`, not sure because can be replaced with `x => x.foo || defaultValue`
- `propEq `, not sure because can be replaced with `x => x.foo === value`
- `nth`, not sure because can be replaced with `x => x.foo[1]`
- `length`, not sure because can be replaced with `x => x.length`
- `includes`,  in ramda https://ramdajs.com/docs/#includes they support string, objects, and arrays, we can do something similar
- `has` we can add it
- `assoc`, we can use `merge` instead
- `assocPath`, it could be good to have it, but it can be non-trivial to implement or there can be many use cases. For example: updating arrays. Maybe it's better to use `immer` library?
- `tail`, `init`,  we can add it, but how often people use such functions?
- `debounce`, `throttle`, it would be good to have it. Something similar to lodash, but with a single `options` argument.

> would find helpful, would be a short introduction about how to implement lazyness,

You can check the source code for `uniq` and `take`
https://github.com/remeda/remeda/blob/master/src/take.ts
https://github.com/remeda/remeda/blob/master/src/uniq.ts

```ts
export type LazyResult<T> = LazyEmpty<T> | LazyNext<T> | LazyMany<T>;

interface LazyEmpty<T> {
  // true if function should stop processing more elements
  // for example `take(3)`, should stop after 3rd element
  done: boolean;
  // true, if there is  a result (output value)
  // for example: `uniq`, can return `false` if there is a duplicated element
  hasNext: false;
  // true, if there are multiple result
  // for example: `flatMap`, can return multiple items
  hasMany?: false | undefined;
  // the value to output
  next?: undefined;
}

interface LazyNext<T> {
  done: boolean;
  hasNext: true;
  hasMany?: false | undefined;
  next: T;
}

interface LazyMany<T> {
  done: boolean;
  hasNext: true;
  hasMany: true;
  next: T[];
}
```

**Comment by sobstel** [comment]
> * `debounce`, `throttle`, it would be good to have it. Something similar to lodash, but with a single `options` argument.

I believe it should out of scope of library like this and `debounce` and `memoize` is covered by https://github.com/developit/decko already.

**Comment by SirJayEarn** [comment]
Sorry for the long delay!
In the meantime a bunch of these functions from my initial comment are no longer required I think, because with the latest typescript releases this can be achieved with vanilla typescript.
So I think what is still left is just: `uniqBy`, `includes`, `has`, `debounce` and `throttle`
I just looked into `immer` - looks very interesting. Somehow I don't like the idea of introducing a dependency though. So I would postpone `assocPath` for now.
And in the future `is` can be discussed.

**Comment by SirJayEarn** [comment]
Fiddling around with haskell a little lately, what I used pretty often was: `words`, `unwords`, `reverse`, `show`, `read`, `zip` and `unzip`.
These might also be helpful - what do you think?

**Comment by sobstel** [comment]
I wonder how much of these really need to be added. I personally think 1-liners should be rather documented (in mapping?) and 

Samples:

* `includes` -> `!!find`
* `reverse` -> `array.reverse()`
* `words` -> `string.split(/\s+/)`
* `unwords` -> `string.join(' ')` 

But I'm just a lib user. @lstkz What's your take on this? There's already 1-liners in the lib eg [toPairs](https://github.com/remeda/remeda/blob/master/src/toPairs.ts#L11).

Personally I'd prefer the lib to provide only those things that are absolutely required.

**Comment by lstkz** [comment]
I am fine with `includes`, and `reverse` (`array.reverse()` mutates the array).  
`words`, and `unwords` are simple 1 liners, and they are not core functions.
Can you explain `show`, `read`, `zip`, `unzip`?

**Comment by SirJayEarn** [comment]
`show` basically just converts to string. So it could be implemented as ```const show = (arg: any) => `${arg}`;```. Or we could think about doing JSON.stringify for objects, but idk.

`read` is the opposite of `show`. I used it mostly for converting strings to numbers. So this would do something like `const read => parseFloat`. So this is not really required I just realized :D

`zip` combines two arrays into one array by putting elements of same index in a tuple. Like this: `zip([1,2,3], ['a','b','c']) // returns [[1, 'a'], [2, 'b'], [3, 'c']]

`unzip` is the reverse of that: `unzip([[1, 'a'], [2, 'b'], [3, 'c']]) // returns [[1,2,3], ['a','b','c']]`

**Comment by vladimiry** [comment]
> const show = (arg: any) => `${arg}`;

You could use `String` as a function (without `new` keyword).

> array.reverse() mutates the array

`[...].reverse()` immutable version.

**Comment by leilapearson** [comment]
Could add something like this to mapping.md for one-liners?

```markdown
### Helpful one-liners

Some lodash and ramda functions don't have a Rameda equivalent, but can be 
easily replaced with a one-liner in TypeScript. Some of the most common
are listed below.

| Lodash         | Ramda               | TypeScript                          |
| -------------- | ------------------- | ----------------------------------- |
| `isNil`        | `isNil`             | `x => x == null`                    |
| `-`            | `path`              | `a?.b?.c`                           |
| `property`     | `prop`              | `x => x.a` or `x => x[n]`           |
| `-`            | `propOr`            | `x => x.a || defaultValue`          |
| `-`            | `propEq`            | `x => x.a === value`                |
| `nth`          | `nth`               | `n => a[n]`                         |
| `words`        | `-`                 | `string.split(/\s+/)`               |
```

**Comment by vladimiry** [comment]
> `x => x.a || defaultValue`

I guess you meant `x => x.a ?? defaultValue` (`Nullish Coalescing` / `??` thing supported in TS since 3.7);

**Comment by sobstel** [comment]
> Could add something like this to mapping.md for one-liners?

+1 from me. I think that it's better to promote best practises rather making remeda overly bloated. If you start a PR, I (we?) can help with this.

**Comment by SirJayEarn** [comment]
> Could add something like this to mapping.md for one-liners?
> 
> ```gfm
> ### Helpful one-liners
> 
> Some lodash and ramda functions don't have a Rameda equivalent, but can be 
> easily replaced with a one-liner in TypeScript. Some of the most common
> are listed below.
> 
> | Lodash         | Ramda               | TypeScript                          |
> | -------------- | ------------------- | ----------------------------------- |
> | `isNil`        | `isNil`             | `x => x == null`                    |
> | `-`            | `path`              | `a?.b?.c`                           |
> | `property`     | `prop`              | `x => x.a` or `x => x[n]`           |
> | `-`            | `propOr`            | `x => x.a || defaultValue`          |
> | `-`            | `propEq`            | `x => x.a === value`                |
> | `nth`          | `nth`               | `n => a[n]`                         |
> | `words`        | `-`                 | `string.split(/\s+/)`               |
> ```

I also think this would be nice 👍 
I think the `words` implementation is what haskell does, but lodash also trims out non-letter characters like `&` , `#`, `,` etc.  I like haskells way more. If we wanna replicate lodash here the regex is a little more complex though: https://github.com/lodash/lodash/blob/master/words.js#L4

**Comment by leilapearson** [comment]
Sure, I can start a PR. Help is very much appreciated though. I'm not what anyone would call an expert on Typescript or on functional programming - which is why I value documentation like this enough to chime in! :-). 

Fortunately these are generally simple functions - but good catch already on the "??" versus "||" -- and the lodash implementation of `words` too.  I'll remove that one from the list since it is more complicated when considering unicode vs ascii as well as non-letter characters.

**Comment by leilapearson** [comment]
Created PR #53  -- together with some questions for you all...

**Comment by digimuza** [comment]
> If you think there are core functions are missing, then I will be happy to accept PRs, but some functions from lodash/ramda are 1-liners.
> 
> * `isNil`, I think it's not needed because it can be replaced with `x => x == null`
> * `defaultTo` we can add it
> * `is`, not sure how to implement it, and I don't like ramda implementation https://ramdajs.com/docs/#is. Currently, I always use `typeof` or `Array.isArray`. We can discuss it in a separate issue.
> * `uniqBy` we can add it
> * `path`, I think it's not needed because in the new typescript version we can use `a?.b?.c` syntax
> * `prop`, not sure because can be replaced with `x => x.foo`
> * `propOr`, not sure because can be replaced with `x => x.foo || defaultValue`
> * `propEq `, not sure because can be replaced with `x => x.foo === value`
> * `nth`, not sure because can be replaced with `x => x.foo[1]`
> * `length`, not sure because can be replaced with `x => x.length`
> * `includes`,  in ramda https://ramdajs.com/docs/#includes they support string, objects, and arrays, we can do something similar
> * `has` we can add it
> * `assoc`, we can use `merge` instead
> * `assocPath`, it could be good to have it, but it can be non-trivial to implement or there can be many use cases. For example: updating arrays. Maybe it's better to use `immer` library?
> * `tail`, `init`,  we can add it, but how often people use such functions?
> * `debounce`, `throttle`, it would be good to have it. Something similar to lodash, but with a single `options` argument.
> 
> > would find helpful, would be a short introduction about how to implement lazyness,
> 
> You can check the source code for `uniq` and `take`
> https://github.com/remeda/remeda/blob/master/src/take.ts
> https://github.com/remeda/remeda/blob/master/src/uniq.ts
> 
> ```ts
> export type LazyResult<T> = LazyEmpty<T> | LazyNext<T> | LazyMany<T>;
> 
> interface LazyEmpty<T> {
>   // true if function should stop processing more elements
>   // for example `take(3)`, should stop after 3rd element
>   done: boolean;
>   // true, if there is  a result (output value)
>   // for example: `uniq`, can return `false` if there is a duplicated element
>   hasNext: false;
>   // true, if there are multiple result
>   // for example: `flatMap`, can return multiple items
>   hasMany?: false | undefined;
>   // the value to output
>   next?: undefined;
> }
> 
> interface LazyNext<T> {
>   done: boolean;
>   hasNext: true;
>   hasMany?: false | undefined;
>   next: T;
> }
> 
> interface LazyMany<T> {
>   done: boolean;
>   hasNext: true;
>   hasMany: true;
>   next: T[];
> }
> ```

Hello I recently discovered this amazing library. 
In following weeks I will make some pull requests to solve issues that are deal breakers for me 😁
Currently filter function does not support type guards. And this is not Typescript friendly at all.

Because of this reason And I will disagree with you we need function like isNil. Because x == null is not a proper solution for typescript. Typescript need guards to correctly, resolve type data. We also should include some additional simple guards like
`isNil` `isString` `isNumber` `isBoolean` `isFunction` `isArray` `isObject` `isDate` `isDefined` 
`isError`

**Comment by thehappycoder** [comment]
I'd use tail for this use case when I don't need head, only tail:
```
const arr = ['a', 'b', 'c']

zip(arr, tail(arr))
```

But then I'll also need zip to return the last pair: ('c', undefined)

**Comment by Bessonov** [comment]
mapping.md should be linked in README.md as one of the first section.

I think addition of type guards would be useful. They are not hard, but it's better to have a set of standard guards instead of googling and at the end to have different implementations in the same code base. And especially following constructs make code more readable and consistent:

```typescript
[1, null, '3'].filter(isNumber)
```

instead of like:

```typescript
[1, null, '3'].filter((value: any): number => typeof value === 'number')
```
.

But I can understand the view, what one-lines shouldn't bloat the library. What do you think about `src/community.ts` or split between `@remeda/core` and `@remeda/community`?

**Comment by maxfi** [comment]
https://github.com/remeda/remeda/pull/67 includes a bunch of type guards. @TkDodo mentioned that these could possibly get merged. cc @digimuza

**Comment by eranhirsch** [comment]
for housekeeping I think we should close this issue, we can start a new discussion on future plans with the perspective of 2023 eco-system and community needs. @TkDodo wdyt?
