### ISSUE TITLE
Compose isNil and isEmpty

### ISSUE THREAD

**Issue by norbornen** [remeda/remeda#381]
Hello!

How to compose functions isNil and isEmpty (like isNilOrEmpty) and its return types?

**Comment by eranhirsch** [comment]
Hey, some more context would really help in understanding what you are trying to achieve and what would be the ideal solution for it.

If you are filtering, you can pipe 2 filters one after the other, the performance cost over a single filter would be negligible in a pipe because filter is lazy-evaluated.

```ts
const result = pipe(
  data,
  filter(isDefined),
  filter(isEmpty),
);

**Comment by norbornen** [comment]
Hi! Thank you for your attention to my question.

I need two universal type-safe functions that take an argument of any type:

function "isNilOrEmpty" returns `true` if the argument is equals `null`, `undefined`, `"`, `[]`, `{}`
behavior is the same as when calling `(!isDefined || isEmpty)`

function+guard "notNilOrEmpty" returns `true` if the argument is not `null`, `undefined`, `"`, `[]`, `{}`
behavior is the same as when calling `(isDefined && !isEmpty)`.

Thanks.

**Comment by TkDodo** [comment]
I had a very similar issue today, trying to get an `isNonEmpty` util:

```
import * as R from 'remeda'
const data: Array<string> = []

const isNonEmpty = R.isNot(R.isEmpty)

if (isNonEmpty(data)) {
  console.log(data[0].toUpperCase())
}
```

this has two issues ([TypeScript playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAcigFMQSATZQgKBoGMIA7VeKmZALjgEEopkATwA8rKMCYBzAHxwAvHADaAXTqMW8YKgByzAKLgYg+ZgB0W3TAAUGc6gNgjASjrBscKxf2HBV9sicnOABvGjg4dVQIABsSU2iIST9kDkUABmVTGAgAVTAwEigAYTQSK0CaAF8gA)):

1) `isNonEmpty` only accepts. Locally, I'm getting:
```
TS2345: Argument of type 'string[]' is not assignable to parameter of type 'null | undefined'.
```
but the sandbox shows a different error

2) This is more of a feature request, but after the `isNonEmpty` check, accessing [0] should be safe even under `noUncheckedIndexedAccess`.

In the past, I've made my own util for this:

```
type NonEmptyArray<T> = [T, ...Array<T>]
const isNonEmpty = <T extends unknown>(
  array: Array<T>
): array is NonEmptyArray<T> => array.length > 0
```

We already have the `NonEmptyArray` type in remeda internally, but I'm not sure if we could get this to work without a dedicated util

**Comment by eranhirsch** [comment]
Typescript doesn't infer the "else" part of a negated condition in most cases, that's why it's really hard to type a ternary operator for pipes, e.g.
```
const x = pipe(
  data,
  doSomeCalculation(),
  branch(typePredicate, (narrowedType) => { ... }, (elseTyped) => { ... }),
);
```

`elseTyped` would have to be typed the same as the input, we can't "remove" the narrowedTpe from it.

This means that we can't simply compose R.isNot() on a different condition to get the opposite. We need to implement the not version of types that make sense.

In my own projects I use a `hasAtLeast(array, N)`. I've been wanting to push this to remeda for a while but these recursive tuple types are cumbersome once you want to use N that isn't small (like `hasAtLeast(array, 1000)`).


```ts
import { purry } from "remeda";
import type { ReadonlyTuple } from "type-fest";

/**
 * An array of type T which has AT LEAST N members.
 *
 * IMPORTANT: The result is not readonly, Wrap it with Readonly if that's what
 * you need.
 */
export type ArrayMinN<T, N extends number> = number extends N
  ? never
  : N extends 0
  ? never
  : [...ReadonlyTuple<T, N>, ...T[]];
/**
 * Refines an array to a tuple of items T that has AT LEAST Min items of type T.
 *
 * @see hasAtMost to define just an upper bound on array length
 * @see isBounded to define both upper and lower bounds on array length
 * @see isLength to define an exact length.
 */
export function hasAtLeast<T, N extends number>(
  data: readonly T[],
  minimum: N,
): data is ArrayMinN<T, N>;

export function hasAtLeast<T, N extends number>(
  minimum: N,
): (data: readonly T[]) => data is ArrayMinN<T, N>;

export function hasAtLeast(...args: readonly unknown[]): unknown {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-return
  return purry(hasAtLeastImplementation, args);
}

const hasAtLeastImplementation = <T, N extends number>(
  data: readonly T[],
  minimum: N,
): data is ArrayMinN<T, N> => data.length >= minimum;
```
