### ISSUE TITLE
Add `seed` parameter to randomization functions

### ISSUE THREAD

**Issue by gustavopch** [remeda/remeda#407]
For example, I'd like to have the same deterministic result if I call `R.sample(array, size, { seed })` multiple times. The `seed` parameter should be added not only to this function, but to all those that produce randomized results.

**Comment by eranhirsch** [comment]
afaik JS doesn't provide an API to seed the random number generator, and we rely on the native random number generator in our random functions

**Comment by gustavopch** [comment]
Yeah, I think it doesn't. To avoid breaking changes, Remeda could provide 2 behaviors: (a) use a custom random number generator when `seed` is passed and (b) use the native one otherwise.

For reference, I'm using this function in my project:
```ts
// Adapted from: https://gist.github.com/blixt/f17b47c62508be59987b?permalink_comment_id=2682175#gistcomment-2682175
export const randomNumber = ({ seed }: { seed?: number } = {}): number => {
  seed ??= Number(String(Math.random()).split('.')[1])
  seed = (seed + 1831565813) | 0
  let x = Math.imul(seed ^ (seed >>> 15), 1 | seed)
  x = (x + Math.imul(x ^ (x >>> 7), 61 | x)) ^ x
  return ((x ^ (x >>> 14)) >>> 0) / 2 ** 32
}
```

**Comment by eranhirsch** [comment]
The problem with seeding is that (I think) there's an expectation that it would be global. You expect to call a seeding function somewhere at the start of the computation (or the whole session) and then call the RNG to get random numbers from that "set". The function you suggested would always return the same single number every time it's called, so calling:
```ts
const seed = 1;
const myRandomArray = [randomNumber({ seed }), randomNumber({ seed }), randomNumber({ seed })];
```
would result in an array with the same number 3 times, whereas without the seed the numbers would be different. This difference is not obvious, can result in a lot of bugs, and is probably not even good for tests.

because Remeda doesn't have any global state (and it shouldn't, because it's just a bunch of functions) then there's no place to store the seed.

I just don't see how this fits into Remeda as a simple library of utility functions. If you have an example from lodash/underscore/ramda/etc... that solved this issue I'd be happy to take another look

**Comment by markmiro** [comment]
Finding this issue after considering using sample based on a React router's `location.key`. The idea is I want to show the same recommendations when the user uses the back button.

In my case, I'm not looking for a global var set to seed (the way fakerjs does it).

Also think the API that @gustavopch suggested would work for my uses:
```
R.sample(array, size, { seed })
```

**Comment by gustavopch** [comment]
Yeah, that's the kind of use case I have in mind. Another common one: generate the same output on the server and on the client to prevent hydration issues.

**Comment by gustavopch** [comment]
FWIW, found this pseudo-random number generator https://www.npmjs.com/package/prando with 732B.

**Comment by eranhirsch** [comment]
Thanks for the suggestion and for looking into possible solutions. I'm still not convinced that this feature fits Remeda well.

The way `purry` works to make dataLast and dataFirst work in tandem doesn't jive with optional parameters to functions. I don't think `seed` should be made a required parameter for shuffling or sampling, so I don't see how this would fit. 

I also have concerns over the statefulness of seeded random algorithms or the confusion that might happen due to it not being stateful.

If more robust randomization features are required, a general-purpose utility library is not the right place to look for them. In contrast, more mathematical/statistically oriented libraries might be more appropriate. I admit that I don't have a suggestion for such a library.

**Comment by gustavopch** [comment]
I understand your position. Two possible workarounds:
- To avoid hydration issues with React, generate the value once on the server and send it to the client instead of generating multiple times directly in the render function.
- For other cases, use some sort of keyed memoization and pass the same key when you want the same value.

**Comment by eranhirsch** [comment]
Would it be OK with you @gustavopch that we close this task?

**Comment by gustavopch** [comment]
Sure, I'm closing it.
