### ISSUE TITLE
`isObject` documentation is slightly off

### ISSUE THREAD

**Issue by stwlam** [remeda/remeda#414]
The current doc for `isObject` is:

> A function that checks if the passed parameter is of type Object and narrows its type accordingly

This isn't quite right:
- `isObject([])` returns `false` but is an `Object`
- `isObject(Object.create(null))` returns `true` but isn't an `Object`

Accounting for those could make the documentation a little verbose, but it is perhaps at least important to call out that an array will not be counted among "objects".

**Comment by eranhirsch** [comment]
Actually going over Lodash and the PRs that introduced this guard, it wasn't clear to me that the exclusion of arrays was intentional. I think it just made sense at the time. Lodash has 2 guards, one for just the type-check (`isObjectLike`) and one for simple Records (`isPlainObject`).

I've sent a PR that takes a similar approach and introduces 2 new guards, and deprecates this one instead.

Thanks for pointing this out!

**Comment by stwlam** [comment]
Thanks for looking into this! I suppose what originally caught my eye was that `Object` is capitalized in the docs, seemingly implying that `isObject(x)` is true if and only if `x instanceof Object`. Instead it guarantees that `typeof x === "object"` and is neither an array nor equal to `null`.
