### ISSUE TITLE
Request to not remove compact

### ISSUE THREAD

**Issue by LandonSchropp** [remeda/remeda#444]
Hello again. 👋 

I noticed that `R.compact` is deprecated. I'd like to request that it be left in.

Here's a real-world example of where I think it's useful.

``` typescript
return R.pipe(
  new Chess(fen).board(),
  R.flatten(),
  R.compact,
  R.map(({ square }) => square),
);
```

To me, this is just a tad bit easier to read than this (especially coming from Ruby where `compact` is very common):

``` typescript
return R.pipe(
  new Chess(fen).board(),
  R.flatten(),
  R.filter(R.isTruthy),
  R.map(({ square }) => square),
);
```

Not a big deal either way, but I thought I'd make the request. 🙂

**Comment by eranhirsch** [comment]
My issue is that any changes, refactors, and fixes performed to `filter` are not automatically inherited by or ported to `compact`, so the two can easily drift (like they already have where compact isn't lazy).

But even if we make compact use `filter` under the hood, there's still the issue with discoverability where users won't be sure how they differ (without looking at the code, which most users don't do), and therefore won't understand which one they should use. In a library with increasingly more functions, each redundant one adds more noise.

I envision implementing certain other functions with `filter` and creating a category "Filters" to help users discover them, e.g. set functions like `intersect` and `difference`.

I prefer an opinionated set of easily composable functions rather than incorporating every use case as a first-class function.

**Comment by TkDodo** [comment]
I think understanding `compact` depends on your background. ruby has `compact`, which removes falsy values. Python also has it, but has a different concept of falsy. In php, it does something completely different.

I honestly understand better what `R.filter(R.isTruthy)` does vs `R.compact`, because it's more explicit.

**Comment by LandonSchropp** [comment]
Fair points. I appreciate the insights. 🙂

**Comment by ConnorSinnott** [comment]
Is there any avenue to petition for this to be reopened? I too am looking at Remeda as a replacement for lodash and was disappointed to see that `compact` was not available. Reducing an array of `T | undefined` to `T` is a frequent operation in JavaScript (in the repos I work with, probably the most frequent operation with lodash). So `_.filter(arr, _.isTruthy)` being more verbose is a double-edged sword. As mentioned by @TkDodo, each language might have a different implementation of `compact`, but they _both have_ implementations of compact. If nothing else, this lowers the bar for migration from lodash since refactoring `_.compact` to `_.filter(arr, _.isTruthy)` is a noisy refactor.

**Comment by eranhirsch** [comment]
Each language has an idiomatic way to do compact, and in JS, it would be `array.filter(Boolean)`; This would be obvious and clear to any JS developer who doesn't specifically work with Lodash.

The problem is actually in Typescript, which doesn't infer the usage of Boolean as we'd expect (see, for example, the ts-reset project's solution: https://www.totaltypescript.com/ts-reset; unfortunately, their docs don't support deep-linking, so you'd need to scroll down). Typescript 5.5 (in beta now) has a fix for this built-in, by allowing inferred type-predicates, so the code above should just work.

We don't have a goal with Remeda to be a drop-in replacement for Lodash; we change names, APIs, and runtime behavior when we feel Lodash did something we don't agree with. Lodash was built in a different runtime environment with different concerns and goals, and since then, it has had to stay somewhat backward-compatible with these prior decisions.

In a highly typed and strict project, the kind we want to help people maintain with Remeda, we felt that filtering on "truthy" should be discouraged, as you might be over-shooting what you wanted to filter. You'd be better off filtering on `undefined` (`isDefined`), `null` (`isNonNull`), empty strings (`isEmpty`), and `0` (`(x) => x !== 0`). We still offer `isTruthy`, but offering the composition of `filter` does not match our goals for the library.
