### ISSUE TITLE
Add string manipulation utilities like camelCase, startCase, etc

### ISSUE THREAD

**Issue by viveleroi** [remeda/remeda#457]
We're hoping to replace lodash and ramda entirely with remeda. There are a few functions remeda doesn't have that I believe it could benefit from.

Common string manipulation methods are one of the reasons we still use lodash in addition to ramda - ramda decided those kinds of utility functions weren't appropriate for the library. I'm hoping remeda is willing to add them.

The below links are for camelCase but these would easily apply to all similar functions.

[Lodash docs](https://lodash.com/docs/4.17.15#camelCase)
[Lodash source](https://github.com/lodash/lodash/blob/main/src/camelCase.ts)

**Comment by eranhirsch** [comment]
I'm supportive of this, can you send a PR?

**Comment by cjquines** [comment]
related: #525

**Comment by Brodzko** [comment]
Does this mean that the stance taken in [this issue](https://github.com/remeda/remeda/issues/207#issuecomment-1213081826) has changed now? If that is the case, I'm happy to help

**Comment by eranhirsch** [comment]
We have more capacity to support these requests now and can accept more additions to the library. Take a look at the open PRs before you send something out, there might be a PR open already for some of these cases

**Comment by AndreaPontrandolfo** [comment]
I think only a subset of Lodash string utilities should be prioritized to make it into Remeda. Since Lodash was created, some string utilities were made part of Ecmascript and so made Lodash alternatives obsoletes.

`startWith`: not needed. There is already a vanilla counterpart.
`endsWith`: not needed. There is already a vanilla counterpart.
`split`: not needed. There is already a vanilla counterpart.
`replace`: not needed. There is already a vanilla counterpart.
`parseInt `: not needed. There is already a vanilla counterpart.
`trim`: not needed. There is already a vanilla counterpart.
`trimStart`: not needed. There is already a vanilla counterpart.
`trimEnd`: not needed. There is already a vanilla counterpart.
`camelCase`: yes.
`snakeCase `: yes.
`kebabCase `: yes.
`truncate `: yes.
`startCase `: yes. Note: In some other libs this is also called "titleCase".
`capitalize `: yes. [PR open](https://github.com/remeda/remeda/pull/525)

Im not gonna mention the other string methods as they are not really common or useful.

But in general, yes, i strongly believe these types of utilities should be part of Remeda, they are extremely handy in Lodash.

**Comment by eranhirsch** [comment]
All functions we were considering for this are now part of the library
