### ISSUE TITLE
Add round

### ISSUE THREAD

**Issue by viveleroi** [remeda/remeda#462]
We're hoping to replace lodash and ramda entirely with remeda. There are a few functions remeda doesn't have that I believe it could benefit from.

I'm currently using `round` from lodash and would like to see it added. 

[Lodash docs](https://lodash.com/docs/4.17.15#round)
[Lodash source](https://github.com/lodash/lodash/blob/main/src/round.ts)

**Comment by paolostyle** [comment]
I have the same need and I was planning to contribute it, I'll try to prepare a PR soon

**Comment by viveleroi** [comment]
> I have the same need and I was planning to contribute it, I'll try to prepare a PR soon.
> 
> edit: welp that's a freaking rabbit hole if I ever saw one and literally every implementation will have some weird edge cases due to how double precision floats work. If we go by the `The implementation of each function should be as minimal as possible.` design goal from the readme I guess the answer is simple but on the other hand I bet there will be many issues reported regarding this function. At the same time this is a very useful function and perhaps the 1% of cases is not worth the hassle. I'd love to hear from the maintainers.

Lodash's version is funky but probably the best bet for compatibility. I'd use it directly but am not sure where the maintainers stand on using code like that. Both projects are MIT licensed so I see no problem.

https://github.com/lodash/lodash/blob/main/src/.internal/createRound.ts

**Comment by eranhirsch** [comment]
We can't support an optional precision param in Remeda because of how the library handles currying of functions during runtime: Remeda looks at the **number of params** a function was called with and decides if it should return a curried function (dataLast) or the result of running it (dataFirst). Because `precision` and `data` are of the **same type** (number) when `round(<number>)` is called, we won't be able to tell if this is a dataLast call where <number> is precision or a dataFirst call where <number> is the data itself and precision was omitted.

This means that the only thing Remeda can provide is the standard `Math.round` function. Because typing is trivial there's nothing Remeda can bring to the table that isn't already part of the native implementation. I'm not sure there's anything left to provide here as you can always do:

```ts
const x = pipe(
  data,
  ...
  Math.round,
  ...
);
```

**Comment by eranhirsch** [comment]
I saw the implementation in #463 that makes the precision a required parameter. That is also an acceptable solution.

Regarding MIT, it's fine to take the code from Lodash, but to be good sports, we should attribute Lodash and provide a link to their implementation in the code itself.
