### ISSUE TITLE
How to force type of function builder

### ISSUE THREAD

**Issue by stychu** [remeda/remeda#493]
How  can I force the type for the omit and then use it with the data. Typescript is yelling at me with the second example

```ts
    const { currentSchema, allSchemas } = ctx.schemas.toJSON();
  
    return {
      currentSchema: R.omit(currentSchema, ['entityDefinitions']),
      allSchemas: R.flatMap(allSchemas, R.omit(['entityDefinitions'])),
```

 vs
  
```ts
const { currentSchema, allSchemas } = ctx.schemas.toJSON();
    const omitDefinitions = R.omit(['entityDefinitions'])

    return {
      currentSchema: omitDefinitions(currentSchema),
      allSchemas: R.flatMap(allSchemas, omitDefinitions),
    };
      ```

**Comment by eranhirsch** [comment]
Because of typescript limitations we can't support both a "stand-alone" dataLast `omit` function and a "piped" dataLast `omit` function, and because the main purpose of dataLast is for "piped" use-cases that's what we opted for. You can define the specific type via a generic if that's what you need:
```ts
const omitter = R.omit<MyType>(['someField']);
//    ^? (data: MyType) => Omit<MyType, "someField">
```
