### ISSUE TITLE
`reject` type guards broken?

### ISSUE THREAD

**Issue by jaens** [remeda/remeda#503]
```typescript
import R from "remeda";
let arr: (something | undefined)[] = [];
```

This code's types:
```typescript
R.pipe(
  arr,
  R.reject(R.isNil)
)
```

are not equivalent to:

```typescript
R.pipe(
  arr,
  R.filter(R.isNot(R.isNil))
)
```

The former (ie. reject) does not narrow the types to exclude `undefined`.

**Comment by eranhirsch** [comment]
I didn't even know we have a `reject` function :). I don't think we need 2 filter functions, seems like a candidate for deprecation, @TkDodo, wdyt?

As for the question, Typescript doesn't provide a way to get the "else" part of a type predicate, not via a utility type, and not even directly in a condition:

https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiAq5oF4oG8oA8D8AuKARABYQA2pA9gQNxQj4EDuFATqQCYFQC+1AUHwBmAVwB2AY2ABLCqKhEAhgGcAGgApM+OIkgBKfJihSlUAPIBbKcAA82pABpCmAgD4oAMigAFKeIDW1gBKEACOwlIsEOy2CEgujgTObmh8UFCRwMIscolcUnKY-NwCIhLSslCCFBRq7ArAClqxeuipRoJQaoqqtfUKurqtaWniskrA6Fg8UKh1DfzD6RCZ2VgLwwD0G4tQAHrYbdxQZErQKYujouOThkezfetpGVkFj1BbO-uHfMVAA

Because of this, we can narrow the type of the items in the output of `reject` based on the type predicate. This further enforces why we should deprecate `reject`.
