### ISSUE TITLE
docs: put mapping in jsdoc

### ISSUE THREAD

**Issue by cjquines** [remeda/remeda#519]
it'd be nice to have the mapping on the docs website; right now it's not mentioned

options:
1. link it on `index.astro` (aside: this has diverged from the repo `README.md`; should that be changed?)
2. parse `mapping.md` to a file that we can in `docs/src/data`, then read it for `mapping.astro`
3. replace `mapping.md` with a data file in `docs/src/data`, then read it for `mapping.astro`
4. make new jsdoc tags, say, `@lodash` and `@ramda`, then read existing jsdoc output for `mapping.astro`

(and other options are possible too)

i personally like 4

**Comment by eranhirsch** [comment]
We should definitely do 4, and further I think we should drop the mapping concept altogether, and instead improve the search capability so it could look for metadata and not just function names so that searching for the lodash or ramda name would bring up the equivalent function.

I think instead of @lodash and @ramda it would need to be a @mapping tag and we'd configure it to take a param and additional text so that it could be written as:
```ts
* @mapping <library> [renamedName] [- additional context/differences/notes]

// Exact copy:
* @mapping lodash 

// Renamed/changes:
* @mapping ramda cond - add `defaultCase()` as last case

// flexible to other libraries we can map to, Hack Standard Library, Python, Go, C, Java, etc...
* @mapping python zip - returns an array, not an iterator
```

**Comment by cjquines** [comment]
while i do think 4 is the best way forward, i think we should at least temporarily do 3; i'll make a pr targeting the beta branch.

**Comment by eranhirsch** [comment]
I'm now convinced that #708 is the better solution. Goodbye mappings!
