### ISSUE TITLE
Updating to 1.45.0 broke types when using pipe

### ISSUE THREAD

**Issue by armincerf** [remeda/remeda#539]
Will add some more detail in the morning as its late here, but perhaps you can reproduce with just this:

- we have some code that uses 'values' in a pipe and since updating to 1.45.2 (have checked and 1.45.0 has the issue, 1.44.1 does not), the type used after values becomes 'unknown'

```
R.pipe(
      permissions,
      R.groupBy((permission) => permission.package),
      R.values,
      R.map((group) => {
.....
```

In the above example, 'group' becomes 'unknown', I think this is because of the changes made to the type of 'values'.

Another issue, if I end a pipe with 'R.values' the type is `const myData: <T extends object>(data: T) => Values<T>` which breaks things though I'm not entirely sure why. Removing R.values from the end of the pipe and wrapping the whole thing in Object.values returns a much better type which doesn't break typechecking.

**Comment by eranhirsch** [comment]
Hi, we're migrating away from this "headless" usage of utility functions in favor of the functional style. Can you see if using `values()` instead of `values` fixes your issues? I still tried to ensure I didn't break existing usages, but something might have slipped...

**Comment by tbui17** [comment]
@eranhirsch 

I was looking into this myself, and did find a way to implement dataLast implementations that supports headless by using conditional generics instead of overloads to allow lazy evaluation of the type signature. However, the tradeoff is that users will not have immediate feedback when the argument they pass into the function is of an invalid type, as the constraint is moved from the generic parameters down into the return type. They would only receive warnings when attempting to access the returned `never` result. It would also be one function signature instead of two, which may interfere with documentation parsing depending on how it was set up (ie. what to do with a JSDoc that has both `@datalast` and `@datafirst` included).

If this change sounds like a good idea, I'd be up for sending a PR for all of the aforementioned functions, and possibly test documentation as well.

## Example
```typescript
type Values<T extends object> = T extends ReadonlyArray<unknown> | []
  ? Array<T[number]>
  : Array<T[keyof T]>;

/**
 * Returns a new array containing the values of the array or object.
 * @param source Either an array or an object
 * @signature
 *    R.values()(source)
 * @example
 *    R.pipe(['x', 'y', 'z'], R.values()) // => ['x', 'y', 'z']
 *    R.pipe({ a: 'x', b: 'y', c: 'z' }, R.values()) // => ['x', 'y', 'z']
 *    R.pipe(
 *      { a: 'x', b: 'y', c: 'z' },
 *      R.values(),
 *      R.first(),
 *    ) // => 'x'
 *    R.values(['x', 'y', 'z']) // => ['x', 'y', 'z']
 *    R.values({ a: 'x', b: 'y', c: 'z' }) // => ['x', 'y', 'z']
 * @pipeable
 * @category Object
 * @dataFirst
 * @dataLast
 */
export function values<T>(
  data?: T
): T extends object
  ? Values<T>
  : void extends T
    ? <T2 extends object>(source: T2) => Values<T2>
    : never;

export function values() {
  return purry(Object.values, arguments);
}

```
## Tests
```typescript
  it('should return never with invalid args', () => {
    expectTypeOf(values(12345)).toBeNever();
  });

  it('should return generic 1-ary curried function when no args are passed', () => {
    const data = { a: 3, b: 4, c: 3 };
    const fn = values();
    const result = fn(data);
    expectTypeOf(result).toEqualTypeOf<number[]>();
  });

  it('should infer type with dataLast', () => {
    const data = { a: 3, b: 4, c: 3 };
    pipe(
      data,
      values(),
      map(numbers => {
        expectTypeOf(numbers).toEqualTypeOf<number>();
      })
    );
  });

  it('should infer type with "headless" dataLast', () => {
    const data = { a: 3, b: 4, c: 3 };
    pipe(
      data,
      s => s,
      values,
      map(numbers => {
        expectTypeOf(numbers).toEqualTypeOf<number>();
      })
    );
  });
```

**Comment by eranhirsch** [comment]
This looks really cool! I think that to reduce friction to a minimum, we would wait to a v2 release of Remeda to do a hard-switch and deprecate the headless versions, and we won't support them starting that version.
