### ISSUE TITLE
Decide on the philosophy and plans for missing Remeda equivalents of Lodash and Ramda functions 

### ISSUE THREAD

**Issue by leilapearson** [remeda/remeda#54]
Thought I'd create a single issue where the community can discuss this issue before we go too far down one path or another. 

Discussion so far has been split across a few  issues and PRs: #37, #29, #53, #10

It would be good to identify:

1. What Lodash and Ramda functions to add eventually + possibly what to do in the meantime
2. What functions NEVER to add + why not + what to do instead
3. What are the rules / guidelines for deciding which functions fit into each category?

Propose that whatever is agreed be documented in mapping.md

**Comment by leilapearson** [comment]
Note that for 1 and 2 above, we don't need to come up with the full list at this point. We just need to come up with enough sample cases to illustrate whatever the rules / guidelines are in point 3.  This discussion is really about point 3. Once that's decided, points 1 and 2 should be easier to answer and document.

**Comment by leilapearson** [comment]
Comment from @sobstel in #53:

> I can see where your confusion comes from, but I don't think we should treat remeda as a ramda clone (neither lodash clone for that matter). The latter is a functional library for JS, the former is a TS utility library.
>
> Saying that, it's much simpler for remeda. prop is a very good example, because it's already implemented. See https://github.com/remeda/remeda/blob/master/src/prop.ts. It's just obj[name]; and we should follow this convention here in mapping file too.
>
> We should also be aware that mappings are not 1-1 as functions between libs sometimes does not match one to one and it's fine. It's just help from people migrating from other libs.

**Comment by lstkz** [comment]
Reasons I don't like lodash:
- Too many functions.
- Every function has many signatures, accepts many data types. For example: `_.pick(obj, 'a', 'b')`, `_.pick(obj, ['a', 'b'])` both formats are supported. If there are many signatures, typescript definitions are hard to read.
- `fp` version is not documented well.
- Lazy evaluation is not well documented. For example: it works with` _.take(1)`, but not with `_.head`.
- Not designed for typescript.
- Some functions are huge. Internally many helpers have many KB.

Reasons I don't like Ramda:
- Authors prefer creating everything as one big function, replacing logical operators, `if` statements by functions.
- Huge problems with typescript typings. I tried to use many definitions, where authors tried to use hacks to cover most use cases, but there were still problems. Another issue is that, when a new typescript version is released, it can break typings.
- There are many functions, that are simple one-liners (especially Math functions).
- I am not sure if following Haskel strictly is a good idea. In Haskel, you have a compiler that catches all problems, but in JS you don't have it.

My current philosophy:
- Don't follow any approach strictly (functional, procedural), but try to find a proper balance.
- Use only things that work well with typescript. For example: We can't implement a `curry` function because it loses all arguments names.
- `data-last` approach is only (or in 99.9% cases) useful inside `.pipe` function.
- All types should be inferred automatically. There should be no need to provide type manually. For example `R.map<ItemType>(...)`. 
- Prefer using inline lambdas where possible.
- Support lazy evaluation where possible.
- Try to implement minimal functions.
- Reuse built-in functions from ES5/6/7/8 (Object.assign, Object.keys, Object.entries, etc).

**Comment by leilapearson** [comment]
Here's a summary of the library descriptions:

**Remeda**:
> The first "data-first" and "data-last" utility library designed especially for TypeScript.
>
> There are no good utility libraries that work well with TypeScript. When working with Lodash or Ramda you must sometimes annotate types manually. Remeda is written and tested in TypeScript and that means there won't be any problems with custom typings.
> . . .
> Remeda implements all methods in two versions, and the correct overload is picked based on the number of provided arguments.
> . . .
> Many functions support lazy evaluation when using pipe or createPipe. These functions have a pipeable tag in the documentation. Lazy evaluation is not supported in Ramda and only partially supported in lodash.
> . . .
> Design philosophy
> 1. The usage must be programmer friendly, and that's more important than following XYZ paradigm strictly.
> 2. Manual annotation should never be required, and proper typings should infer everything. The only exception is the first function in createPipe.
> 3. E6 polyfill is required. Core methods are reused, and data structure (like Map/Set) are not re-implemented.
> 4. The implementation of each function should be as minimal as possible. Tree-shaking is supported by default. (Do you know that lodash.keyBy has 14KB after minification?)
> 5. All functions are immutable, and there are no side-effects.
> 6. Fixed number of arguments.

**Lodash**:
> JavaScript utilities delivering consistency, modularity, performance, & extras.
>
> Lodash makes JavaScript easier by taking the hassle out of working with arrays,
numbers, objects, strings, etc. Lodash’s modular methods are great for:
> - Iterating arrays, objects, & strings
> - Manipulating & testing values
> - Creating composite functions

**Ramda**:
> A practical functional library for JavaScript programmers.
> . . .
> We wanted a library designed specifically for a functional programming style, one that makes it easy to create functional pipelines, one that never mutates user data. . . .
>
> Immutability and side-effect free functions are at the heart of its design philosophy. . . .
>
> Ramda functions are automatically curried . . . The data to be operated on is generally supplied last. 
>
> The parameters to Ramda functions are arranged to make it convenient for currying. . . .
>
> Using Ramda should feel much like just using JavaScript . . .Our basic data structures are plain JavaScript objects, and our usual collections are JavaScript arrays. 
>
> We aim for an implementation both clean and elegant, but the API is king.
>
> Ramda strives for performance. A reliable and quick implementation wins over any notions of functional purity.

**Comment by leilapearson** [comment]
Thanks for the clarifications @lstkz. For extra clarity, I'm just going to extract the parts of your philosophy and descriptions that apply to determining which functions do and do not belong in remeda:

> [Lodash has] too many functions
> Some [Lodash] functions are huge.
> [In Ramda] there are many functions, that are simple one-liners (especially Math functions)
> Use only things that work well with typescript.
> All types should be inferred automatically.
> Prefer using inline lambdas where possible.
> Try to implement minimal functions.

**Comment by sobstel** [comment]
@leilapearson @lstkz It's a great summary. What do you think about adding this to README or CONTRIBUTING file?

**Comment by leilapearson** [comment]
@lstkz - So I think for me the parts I'm not entirely clear on are:

1. What does "too many functions" mean exactly? 
a. Is there a number of functions that is too many? 
b. What is the the source of the concern about having too many? Clutter for users trying to find useful functions? Library size in terms of memory use and impact on application package size?  Burden on library developers and maintainers? 

2. What does "minimal functions" mean? Is it the same as "not too many"? Or is it related to function implementation complexity? 

3. What would make a function "must have" in remeda? "Should have"? "Nice to have"? "Should not have"?

4. Does the audience for this library include people who want to program in a purely functional style?  

- [x] no loops (well, no visible ones ;-)
- [x] pure functions - no mutations
- [ ] programs that consist of many pure functions composed together that transform data according to business rules

You mentioned you don't like the "one big function" philosophy in Ramda. For the people who are trying to build programs that way, what does that mean in terms of them using remeda?

**Comment by leilapearson** [comment]
@sobstel possibly... though I think more of a compare and contrast table format would be better for something like that. I was just trying to get my head around things here.

**Comment by konradekk** [comment]
Glad that I found this conversation as I came here looking for a decent FP library having first heard of ramda and knowing the existence of lodash.

Only few simple functions of lodash were used in the project I’ve been few years ago: especially sorting (by key etc.) or uniqueness filtering; Programming web apps in typescript (only) I was rather an opponent of lodash as it was cumbersome and big with moderate typing support. I’ve even implemented my own version of `clamp` (not sure whether it’s provided in lodash or not). Having quality concerns in mind I’ve considered lodash somewhat a burden and avoided it – also due to perceived lock-in (that’s probably not true); size, i.e. low tree-shakeability, was also a problem for me personally.

Recently I’ve returned to web apps after few years and my team mate mentioned about rambda—I was thrilled to check what it has got after glancing through the docs: after 15 minutes I concluded that it won’t make into the project as this is pile of rubbish without proper typing. This led me here and there in the quest of finding suitable FP library.

Now maybe few words on your average user (i.e. me): apart of having contact with web development few years ago I did mainly typed languages programming: Scala, golang, I liked those more than verbose Java, don’t exactly know pure FP languages like Haskell but understand it somewhat and thinking of it highly.

What I look for in such a lib is quality leap from JS into TS (which is having different aims) similar to the one made from Java into Scala: less bloat and unified API (esp. for containers, streams, monads etc.). I’d definitely use such lib for common array/object mangling, i.e. uniqueness (by key), sorting, reducers, lens for property access and “modification” (producing new values instead of changing old ones according to the FP principles).

I’d most certainly welcome well-based FP construction of the library as it would indicate that API won’t deteriorate easily if made uniform; compatibility with other similar libs would be also a plus but simple migration would be enough to mitigate my lock-in fears. Fantasy-land (and similar standards) is most probably a good thing but only when it serves the API and performance (also important) right.

I’m writing the typings myself but I accept that they simply are and don’t read them if they’re sound and correct—serving their purpose (docs are enough). As for things inside, e.g. loops, those are not important to me if they’re inside and won’t pose problems with the maintenance; pure functions are something that’s “visible” outside so this should be observed—non-pure functions are not tree-shakeable too. As for business needs: when taking into account, that I’m using `redux` and `redux-observable` this is most natural and normal for me.

Hopefully this elaborate voice in the discussion will help to know better (potential) users. :)

**Comment by lstkz** [comment]
@leilapearson 

1. "too many functions"
The number of functions is too big. Many functions are supported natively by the standard library or the language itself.

2. "minimal functions"
We should try to write functions that have a minimal size of code. Many core functions can be implemented in less than 10 lines of code.

3. Not sure about this. We should have functions that are used often.
For example:
We could implement `differenceBy`, but I am not sure if we should add `differenceWith`. IMO it's a very rare function, and for most use cases `differenceBy` is enough.

4. True for all points.

 "one big function"  in Ramda is a function that is one expression.
For example (from Ramda cookbook).

```js
var groupObjBy = curry(pipe(
  // Call groupBy with the object as pairs, passing only the value to the key function
  useWith(groupBy, [useWith(__, [last]), toPairs]),
  map(fromPairs)
))

var diffObjs = pipe(
  useWith(mergeWith(merge), [map(objOf("leftValue")), map(objOf("rightValue"))]),
  groupObjBy(cond([
    [
      both(has("leftValue"), has("rightValue")),
      pipe(values, ifElse(apply(equals), always("common"), always("difference")))
    ],
    [has("leftValue"), always("onlyOnLeft")],
    [has("rightValue"), always("onlyOnRight")],
  ])),
  evolve({
    common: map(prop("leftValue")),
    onlyOnLeft: map(prop("leftValue")),
    onlyOnRight: map(prop("rightValue"))
  })
);
```

Most people prefer functional/declarative style, but they still use normal `if` statements. For example
```js
R.pipe(someData,
  R.filter(x => x.foo > 10),
  R.map(x => {
    if (x.bar) {
      // some code
   } else {
      // some code
   }
  }),
  R.take(10),
)

```

**Comment by MikeyBurkman** [comment]
Just found this library and I'm loving the idea. I loved ramda in JS, but without proper typings in TS (which is not necessarily the library's fault), it's a hard proposition to make these days. My main complaints with lodash are that:
- There are a lot of overloads on functions that make type safety difficult/impossible, and it's really easy to just not even know that a function is not type safe. For instance `_.map(foos, 'nmae')` would compile but is probably a typo. We always suggest using the long-form`_.map(foos, foo => foo.name)`, but that's hard to enforce. (Never mind the mental complexity that having several overrides for each function adds.)
- Lodash's `chain()` function is nice, but few people at my office like using it (for some reason), and you're limited to just lodash functions in it. It's not pretty trying to use lodash extensions with it, and always having to call `.value()` at the end is a bit of annoying boilerplate.
- Some functions mutate the arguments, but it's not obvious without reading through the documentation.

I like that this library seems to be a good compromise between the two. Doing (Ramda) things like `R.map(R.prop('name'))(foos)` can be awesome once you get the hang of it, but (typing issues aside) it's also a bit of a learning curve for people who haven't done much FP. Using pipe() looks more familiar to more mainstream developers, so I think I'd have a much easier time selling it. I just hope it focuses on developer experience over absolute ideology.

**Comment by digimuza** [comment]
My point of view what remeda should be. 

Remeda should be **"typescript"** utility library. 

I will explain what I have in mind. 

1. The library should help work with different typescript types, **unions**. To do that you need guards. Because of this reason I would like that this package include guards like `isString`, `isNil`, `isDefined`, `isNumber`, `isObject`, `isArray`, `isDate`, `isError`, `isFunction`, `isBoolean` `isPromise`, `isRegExp` . I created pull request for that  #67 

In comments, I saw that function like isNil not necessary because you can easily replace this function with `x == null` If this javascript library I would agree with this statement but we working with typescript. And simple expression only affects function output value but not type.
Example 

```typescript
const data = [{ a: 1 }, { a: 2 }, null] // Type ({ a: number } | null)[]
R.filter(data,(x)=>x == null) // Type ({ a: number } | null)[] 
R.filter(data,isNil) // Type ({ a: number })[] // We need guard to alter return type
```

Example of real world use case of guards
```typescript
interface Blog {
  type: 'blog'
  content: string
}
interface Product {
      type: 'product'
      price: number
}
interface Video {
     type: 'video',
     url: string 
}

type Doc = Blog | Product | Video

const docs: Doc[] = [...]

// Complex guard
function isDocType<T extends Docs['type']>(type: T): (data: Doc) => data is Extract<Doc, { type: T }>  {
      return (doc) => {}
}
const params = '?fbId=546465456'

R.pipe(
     docs,
     R.filter(isDocType('video')),
     R.map((video)=>{
                // Video is typeof Video and I can easily access url property
              return `${video.url}?${params}`
     })
)
```

2. The function should never lie about types!! All types should be tested as well. I provided example how to test typescript type in pull request #67 

Example how function can lie 
```typescript
R.pipe(
   docs,
   R.filter((q) => q.type === 'product')
   R.map((q)=>{
        return R.objOf(5, q.type)
   })
) // Incorrect type { product: number, video: number, blog: number  }
// This function should output { product: number } | { video: number } | { blog: number }
```

  c) Focus on utilities that solve common real-world use cases. #65 #66 
     `deepMerge`, `deepSort`, `deepUniq`, `deepEquals` `grouBy`, `sortBy`, `shuffle`, `scan`, `partition`, `clamp`, `difference`, `chunk`.
     And functions like these are unnecessary noise or even harmful.
     `addProp`, `compact`, `concat`, `objOf`, `prop`, `set`

Without these core points, this library is just a javascript library with little better types than rambda :)

**Comment by lstkz** [comment]
1. I am not sure if type guards for primitives are necessary. Usually, we don't have such arrays:
```ts
const arr: Array<number | string | boolean> = []
const arr2 = arr.filter(isNumber);
```
In real projects, we usually mix types that are custom objects
```ts
const arr: Array<Dog | Cat | Bird> = []
const arr2 = arr.filter(isCat);
``` 

2. If there are any bugs, feel free to create a separate issue for it. It's possible that there are edge cases that are not covered.

**Comment by digimuza** [comment]
It really depends on the application and what you trying to achieve. 

```typescript
// This kinda structure is kinda rare :) 
const arr: Array<number | string | boolean> = []
```
More common ones

```typescript
   // From react
   type Children = boolean | null | string | number | ReactElement | ReadonlyArray<boolean | null | string | number | ReactElement>
   const MyAwsomComponent = (props: Children) => {...}
```
Ever tried to write function that supports all data types?

**Comment by lstkz** [comment]
@digimuza 

React children can have many types, but I think we don't filter children by type?
For example, we never write such code:
```ts
const nums = props.children.filter(isNumber);
const strings = props.children.filter(isString);
```
The only useful guard for `filter` is `isNotNull`, but we have `compact` function which does the same thing.
