### ISSUE TITLE
isIncludedIn narrows the negated cases too aggressively 

### ISSUE THREAD

**Issue by jinyongp** [remeda/remeda#603]
```ts
import * as R from 'remeda';

const a1 = [1, 2, 3, 4, 5];
const a2 = [3, 4, 5, 6, 7];

// inferred type is number[]
const r1 = R.difference(a1, a2); // why deprecated?

// inferred type is never[] but should be number[]
const r2 = R.filter(a1, R.isNot(R.isIncludedIn(a2))); // r2 type is never[] but should be number[]

// inferred type is (data: unknown) => data is unknown but should be (data: number) => data is number
const n = R.isNot(R.isIncludedIn(a2));

// inferred type is unknown[] but should be number[]
const r4 = R.filter(a1, n);
```

I think the easiest way to solve the problem is to use `difference` instead of deprecated.

**Comment by eranhirsch** [comment]
Good catch, thanks for reporting, `isIncludedIn` is new and there were obvious edge-cases I missed when adding it. I'll take a look and send a fix for this.

Difference and intersect are deprecated because their semantics are inconsistent with set theory(!) We want to add replacements for these functions using the same name, but to do that, we need to "free up the namespace"; otherwise, we will introduce breaking changes that people will not notice. We added the comment about deprecation so that people can migrate off the existing functions but still have the functionality in the interim and then migrate back to difference and intersect using the new logic once they assess that it makes sense for them (for most people, it will).
