### ISSUE TITLE
Add `sortedUniq`

### ISSUE THREAD

**Issue by felipecrs** [remeda/remeda#627]
https://lodash.com/docs/#sortedUniq

**Comment by eranhirsch** [comment]
I understand the appeal here, especially since lodash already has it, but I can't think of a real-life case where this would have significant performance benefit. How are you using sortedUniq in your product?

**Comment by eranhirsch** [comment]
Also:
```ts
const sortedUniq = filter.indexed(
  data,
  (item, index, array) => index === 0 || item !== array[index - 1],
);
```

**Comment by felipecrs** [comment]
> How are you using sortedUniq in your product?

Not really, I even switched to simpler functions a few hours after opening this issue because my use case was very small.

However, while I can't come up with real use cases now, I believe it should not be rare when users have sorted arrays and need to make them unique. Depending on the size of the array, sortedUniq can produce meaningful improvements.

**Comment by felipecrs** [comment]
That said, I'll understand if you prefer not to add it and close this issue.

**Comment by eranhirsch** [comment]
Yeah, it could be implemented with a simple arrow function in a filter, providing all the benefits of lazy evaluation. I'm also not convinced that this provides any observable perf benefits over using the regular `unique` function (both are O(n) conceptually), and even in real world scenarios it would be hard to find examples where `unique` dramatically fails to do it efficiently.

I'll keep this issue open so that we can add a line recommending the filter approach to the mappings file under the one-liner table.
