### ISSUE TITLE
Add "R" or "Remeda" globally to the docs website

### ISSUE THREAD

**Issue by illiaChaban** [remeda/remeda#661]
When you go to lodash docs, you can open dev tools > console, type "_" and access all lodash methods. This helps with trying things out and expeirmenting. 
It would be nice if Remeda docs had the same feature

**Comment by eranhirsch** [comment]
Sounds like a cool idea

**Comment by eranhirsch** [comment]
I'm not sure this is a good first issue, I don't have a good idea how this is achievable

**Comment by cjquines** [comment]
let me outline what i think the steps are

* in https://github.com/remeda/remeda/blob/master/docs/src/layouts/layout.astro , add the following

```html
<script type="module">
  import * as R from "remeda";
  window.R = R;
</script>
```

* check to see if it works (it should [according to astro docs](https://docs.astro.build/en/guides/client-side-scripts/#client-side-scripts))
* (potentially) change the package.json in docs to include remeda from the top-level directory so the version's always updated

i'll be happy to help anyone who runs into snags

**Comment by eranhirsch** [comment]
It looks cool. I don't want the docs project to import outside of NPM because it creates a lot of weird stuff when using Remeda as a utility library in the docs site. We can work around this by bumping the dependency in the docs package.json every time we publish a version of Remeda using another step in the Github workflow that releases it.
