### ISSUE TITLE
groupBy hidden bug

### ISSUE THREAD

**Issue by digimuza** [remeda/remeda#68]
Currently, the group by function has hidden BUG.

```typescript

interface User {
     prop1: string
}
const data: User[] = [{ prop1: "a" }, { prop1: "b" } ]
R.pipe(
    data,
    R.groupBy((c)=>c.prop1)
) //  { a: [{ prop1: "a" }], b: [ {prop1: 'b'} ] }

// Change in code 
interface User {
     prop1: string[]
}
R.pipe(
    data,
    R.groupBy((c)=>c.prop1)
) //  { "[object Object]": [{ prop1: "a" }, {prop1: 'b'}] }

// Types not complaining no runtime error.
```

Expecting: Typescript should complain that this is not a valid input

**Comment by TkDodo** [comment]
>  to only allow a string for the return type.

I think it should be a bit more exact than that. Maybe `T extends string | number | symbol`, as those are the three things allowed as keys in an object. `mapKeys` had the same issue before I adapted the types, compare here:

https://github.com/remeda/remeda/pull/85

Would you be willing to make a PR?

**Comment by MikeyBurkman** [comment]
@TkDodo As long as the return type is Record<string, T[]>, you won't be able to have the arg return anything other than a string. Though I don't think that would be a breaking change? 
```ts
export function groupBy<T, K extends string|number|boolean|symbol>(
  items: readonly T[],
  fn: (item: T) => K
): Record<K, T[]>;
```

Also, keys in JS objects are always strings (or symbols I suppose), and numbers are booleans are implicitly converted to strings, which could cause some confusing behavior maybe. `obj[true]` and `obj['true']` are the same thing. Lodash has this same issue that has bit me a few times. For instance, `Object.keys(obj)` will return a list of strings, regardless of whether I used numbers or whatever as the grouping key. At work I ended up just writing my own groupBy function that uses a Map as the backing data structure, so that any primitive could be used as the key, though I'm not sure if Remeda really is in the business of trying to define new data structures.

**Comment by TkDodo** [comment]
@MikeyBurkman I think your example code is correct. I would still stick to `T extends string | number | symbol`, as to me, this seems what typescript thinks a PropertyKey of an object can be, according to the lib.es5.d.ts:

https://github.com/microsoft/TypeScript/blob/5305e4a44e4e08c911d181e207602bd4cf335ba1/lib/lib.es5.d.ts#L105

Regarding, Object.keys, there have been many bug reports / feature requests to the typescript repo that it _should_ return `keyof T` (e.g. [this one](https://github.com/microsoft/TypeScript/issues/37495)). They all link to [this stackoverflow](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript) for explanation.

So yeah, technically, we _could_ just align with that. At runtime, it won't make much difference, but I would still think it would be a better developer experience if this code would yield a type error:

```
const obj = { foo: 1, bar: 2 } as const

R.groupBy(obj, () => 'whatever')
```

because `whatever` is clearly not a key of your obj 🤷 .

**Comment by MikeyBurkman** [comment]
Not sure how you're grouping by an object and not an array :P

I'm torn on the whole Object.keys() thing, as it certainly does break down due to TS's structural typing. You could end up with some pretty big runtime errors that the compiler could never prevent. You'd expect Object.keys(Foo) to only return the keys in Foo, but the object just needs to be a subtype of Foo, and thus could have a bunch of fields that aren't in Foo at all. The compiler could not guarantee that the type would be in `keyof Foo` for all keys returned by Object.keys().

Regardless I'll see if I can get a PR up a bit later today or tomorrow with the fix to use use Record<PropertyKey, T[]>

**Comment by TkDodo** [comment]
yes, my example is off 😅 . It should be:

```
const arr = [{ prop1: "a" }, { prop1: "b" } ]

R.groupBy(arr, () => 'whatever')
```

> Regardless I'll see if I can get a PR up a bit later today or tomorrow with the fix to use use Record<PropertyKey, T[]>

👍

**Comment by MikeyBurkman** [comment]
Of course, that'll just result in `{whatever: [{ prop1: "a" }, { prop1: "b" } ]}` lol

**Comment by TkDodo** [comment]
right, I think I _misunderstood_ `groupBy` then, I read the docs now 😅 : https://remedajs.com/docs#groupBy

as long as we return something that is a valid `PropertyKey`, we should be good.

**Comment by TkDodo** [comment]
@digimuza @MikeyBurkman please have a look at the PR: https://github.com/remeda/remeda/pull/135

**Comment by MikeyBurkman** [comment]
Oh man, I was totally going to submit a PR for that later this week! (I kid!)

I like your solution better than what I would have done, anyways. I had never considered doing a type like `NonEmptyArray` before. I'm definitely adding that to my TS toolbox.
