### ISSUE TITLE
`typeof conditional === "object"` for ESM builds

### ISSUE THREAD

**Issue by jinyongp** [remeda/remeda#720]
In version 2.0.5, conditional is an object rather than a function.

This issue has been occurring since version [2.0.0-beta.17](https://github.com/remeda/remeda/releases/tag/v2.0.0-beta.17).

**Comment by eranhirsch** [comment]
Can you provide more context or a repro in codesandbox or TypeScript's playground?

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYwgOwCbBsdBDAGzgF84AzKCEOAIigFMR6M8aBuAKA9TQGd4AHnAC8KdFhz4CACg4B6OXCVwAegH4OSmgAt6BAhBpw8vOPyjA0AcwA0muAG1pAgJQiAfHCHCftAO7QBBg0NnDSbsKeAMzGpjz8ALp2SjwSuGiEAHQY9GR4AK4EMADCJvTS4R5waPR+cAAieDDlLi52LpxAA

**Comment by jinyongp** [comment]
You can check it out [here (codesandbox)](https://codesandbox.io/p/devbox/nest-remeda-test-52x3kj?file=/src/main.ts:17,1).

```ts
// src/main.ts

import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

import * as R from 'remeda';

console.log(R.conditional);        // { defaultCase: [Function: e] }
console.log(typeof R.conditional); // object

// TypeError: R.conditional is not a function
// console.log((R.conditional as any)());

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();
```

**Comment by eranhirsch** [comment]
I managed to reproduce this. The bisects to #596, but that makes me think that maybe that PR just surfaced the fact that our ESM build for this function was always broken. I have a hunch that tsup (or esbuild) is not doing a good job with the `namespace` by using an IIFE to inject the property instead of an `Object.assign`, which is what I would expect would happen.

I'll send out a possible fix.

Thanks for reporting.
