### ISSUE TITLE
R.set possible type regression on v2.2

### ISSUE THREAD

**Issue by cloud-walker** [remeda/remeda#751]
Hi! here the repro: https://stackblitz.com/edit/vitejs-vite-cr6wf4?file=src%2Fmain.ts

If u install the v2.1 it works than on v2.2 gives an error 🤔

**Comment by cjquines** [comment]
this is working as intended, because this could be a type error. consider `foo(setParams, "name", 1)`

i'm not sure how to write `foo` properly here though

**Comment by cloud-walker** [comment]
I think that `foo` should work more with a "pair" tuple, instead of two params that have no direction relation (I mean the field and value)

**Comment by cjquines** [comment]
yeah but even if you wrote `foo<T, K extends keyof T>(..., key: K, value: T[K])` this will still allow `foo(..., "name", 1)` because then `K` can be inferred as `"name" | "age"`.

it doesn't seem like this is a problem with `set` in either case, so i'll close?

**Comment by eranhirsch** [comment]
I was curious about this issue, so I kept it in my todos to see what happened here (mainly because you said it worked in previous versions of Remeda).

Even when the Remeda parts are removed, the code is broken, like @cjquines said, because it allows you to create objects that don't conform to the type that TypeScript says they should conform to.

The weird thing is I don't know why typescript isn't surfacing the typing issue on the setter function. If anything, the Remeda typing now does a *better* job than TypeScript of telling you you are doing something wrong.

https://codesandbox.io/p/sandbox/vigilant-brook-25jr23

**Comment by cloud-walker** [comment]
yeah, I now think too that R.set is working as expected, but I'm full of these dynamic code flows, but I guess its a limit of TypeScript, and I need to re-architect them

**Comment by eranhirsch** [comment]
What you need to do to make it work is constraint all params you need to have a relation between via the generics of the function, in this case what you actually should have done is:
```ts
export function foo<Field extends keyof Person>(
  setParams: (params: ValueOrUpdater<Person>) => Partial<Person>,
  field: Field,
  value: Person[Field]
) {
  setParams((p) => ({
    ...p,
    [field]: value,
  }));
}
```

In general whenever you need to maintain a relationship between params (or return value) you need to pull it "out" to the generics.
