### ISSUE TITLE
`prop` data-last typing should not infer type of data

### ISSUE THREAD

**Issue by estenp** [remeda/remeda#897]
It's possible I'm just missing something, as I'm fairly new to the library, but

```
const isFoo = (o: unknown): o is { foo: string } =>
  R.isPlainObject(o) && "foo" in o;

const a = R.when(isFoo, {
  onTrue: R.prop("foo"),
  onFalse: R.identity(),
});
```

produces TS error: ` Type 'string' is not assignable to type '(data: { foo: string; }, ...extraArgs: any[]) => unknown'.`

Passing `onTrue` a lambda with both arguments works fine.

**Comment by cjquines** [comment]
we should fix the data-last typing of `prop` so that the `data` type isn't inferred on callsite i think

something like

```ts
export function prop<K extends PropertyKey>(
  key: K,
): <T extends Record<K, unknown>>(data: T) => T[K];
```

**Comment by eranhirsch** [comment]
In Remeda we usually don't support what we call "naked" data-last calls (unlike Ramda) where you generate a function via a helper utility and then use that function somewhere else. When you need this kind of logic we usually only support it when it's inlined. This is due to how typescript infers types eagerly and falls back to `any` and `unknown` immediately when it has missing information.

That's one reason you might be experiencing more issues with something like:
```ts
const fooExtractor = R.when(isFoo, ...);
map(data, fooExtractor);
```

vs

```ts
map(data, when(isFoo, ...));
```

Additionally, you don't need to use the extended version of `when` when providing `identity` to the `onElse` branch; that is the default behavior when using the simpler `when(condition, true)` syntax.

Lastly, I observed this issue too while playing with `when` and `conditionally` and concluded that it's only fixable using `NoInfer` which is not supported by our minimum typescript version. The suggestion @cjquines mentioned would break the more common usage of `prop` when the type of T is inferred first (e.g., in `map(prop("a"))`) because typescript would eagerly infer K first. This would break the validation we have that the prop exists in the object.

The only fix I came up with, like the one you suggested, is to wrap the call with an arrow function, which allows the function to be inferred "later".

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg6BjCAO1XmFQDEII4BeOAAoIALjgBXFgGsWEAO4sAlOL6c4Abxy9x7KMBYBzOAF8BAPjpxMAOk4AFADbIDAeQBGAKxKMYIpXAAZIFE2LyEcAZwEPRMrOwoArbyABYkLEJWkdy8ADRZQgAeAfzmtmB4YEW5oeFK+dYA9I1wAHoA-HRK9EA

I'm closing this issue now because I don't think it's fixable until we bump our typescript version, and there is no plan to do that soon.

**Comment by estenp** [comment]
Thanks for the insight @eranhirsch
