### ISSUE TITLE
Issue tree shaking with esbuild 

### ISSUE THREAD

**Issue by wernst** [remeda/remeda#916]
Hi I am trying to bundle some code that uses remeda as a dependency. I am using esbuild as a bundler and the code is going to run in an environment compatible with es2015. I would like to tree shake out code that uses bigint because its incompatible with es2015 and i dont think any imports im referencing use bigint (importing methods like `import { doNothing } from 'remeda'`). Esbuild should perform tree shaking, however the bundler still appears to touch code that references bigint and fails. This may be an esbuild issue, but wanted to flag to the maintainers here.

Specifically I'm referencing: sumBy, shuffle, range, invert, chunk, isArray, intersection, omitBy, isDeepEqual

My current work around is to patch remeda to allow paths like `import { doNothing } from 'remeda/doNothing'` by adding additional entry points (https://nodejs.org/docs/latest-v18.x/api/packages.html#package-entry-points), but id rather not patch the package.

Esbuild issue (with reproduction): https://github.com/evanw/esbuild/issues/3969

**Comment by cjquines** [comment]
hm, this does sound like an esbuild issue. i'll subscribe to the other one

**Comment by eranhirsch** [comment]
This is an interesting issue, but the underlying problem of trying to use Remeda with an es2015 is outside the scope of our project as of version 2.x.x, where the minimum supported version is es2022. Before that version Remeda supported ES5 so if you need a version that is supported in legacy es versions you can try that.

I'm still curious to see how the issue would be resolved on the esbuild side, but it's unlikely that we could offer any solution within Remeda. Feel free to re-open the issue if that turns out to be wrong, and we can fix something on our side.
